// src/components/Canvas.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import events from "../events/index";
  import { ctx as ctxStore } from "../render";
  let canvas: HTMLCanvasElement;
  onMount(() => {
    let ctx: CanvasRenderingContext2D = canvas.getContext("2d");
    if (!ctx) throw new Error("NO CTX??!?");
    scaleCanvasToWindow(canvas, ctx);
    for (const event in events) {
      canvas[`on${event}`] = events[event];
    }
    ctxStore.set(ctx);
  });

  /**
   * Scale the provided canvas to the window.
   * This also makes the resolution correct for high-dpi displays.
   * https://www.kirupa.com/canvas/canvas_high_dpi_retina.htm
   */
  function scaleCanvasToWindow(
    canvas: HTMLCanvasElement,
    ctx: CanvasRenderingContext2D
  ) {
    const size = { width: window.innerWidth, height: window.innerHeight };

    canvas.width = size.width * devicePixelRatio;
    canvas.height = size.height * devicePixelRatio;

    // ensure all drawing operations are scaled
    ctx.scale(devicePixelRatio, devicePixelRatio);

    // scale everything down using CSS
    canvas.style.width = `${size.width}px`;
    canvas.style.height = `${size.height}px`;
  }
</script>

<canvas bind:this={canvas} />

// src/components/Canvas.tsx
import RoadCreator from "../roadCreator/roadCreator";

export default function Canvas() {
    let canvas!: HTMLCanvasElement;
    let ctx!: CanvasRenderingContext2D;

    scaleCanvasToWindow(canvas, ctx);

    const roadCreator = new RoadCreator({
        canvas, ctx
    });
    roadCreator.init();

    return (
        <canvas
            ref={el => {
                canvas = el;
                let tryCtx = el.getContext("2d");
                if (!tryCtx) throw new Error("could not get canvas context");
                ctx = tryCtx;
            }}
            onmousedown={roadCreator.events.onmousedown}
            onmouseup={roadCreator.events.onmouseup}
            onmousemove={roadCreator.events.onmousemove}
            onclick={roadCreator.events.onclick}
        ></canvas>
    )
}

/**
 * Scale the provided canvas to the window.
 * This also makes the resolution correct for high-dpi displays. 
 * https://www.kirupa.com/canvas/canvas_high_dpi_retina.htm
 */
function scaleCanvasToWindow(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
    const size = { width: window.innerWidth, height: window.innerHeight };

    canvas.width = size.width * devicePixelRatio;
    canvas.height = size.height * devicePixelRatio;

    // ensure all drawing operations are scaled
    ctx.scale(devicePixelRatio, devicePixelRatio);

    // scale everything down using CSS
    canvas.style.width = `${size.width}px`;
    canvas.style.height = `${size.height}px`;
}
